name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      # Optional: Run tests (skip or enable based on your needs)
      - name: Run Unit Tests (optional)
        run: |
          pip install -r requirements.txt
          pip install pytest
          pytest || echo "⚠️ Skipping failing tests..."

      - name: Deploy to EC2
        uses: easingthemes/ssh-deploy@main
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}
          remote-user: ubuntu
          server-ip: ${{ secrets.EC2_HOST }}
          target: churn-api

      - name: SSH and Restart App
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd churn-api
            chmod +x start.sh
            ./start.sh
